version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db_name'   
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_password'      
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
  adminer:
    image: adminer
    ports:
      - 8080:8080
